### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by SilentShadowBlade** [tuberp/pong#1]
The game doesn't work. ??

**Comment by tuberp** [comment]
Please explain the problem and steps to recreate it (hardware, OS, etc...)

**Comment by SilentShadowBlade** [comment]
So basically, when I try to clone the code, it says "Error".

**Comment by tuberp** [comment]
OS? Shell? Error message? This seems more likely to be a problem with GitHub rather than the project itself

**Comment by SilentShadowBlade** [comment]
Nope, Github is perfectly functional.

**Comment by tuberp** [comment]
If you fail to provide further information, this thread will be closed

**Comment by SilentShadowBlade** [comment]
LMAO!!

**Comment by SilentShadowBlade** [comment]
LMAO!!
